services:
  command-builder:
    image: ghcr.io/danielraab/command-builder:latest
    container_name: command-builder
    ports:
      - "8080:80"
    volumes:
      - ../public/commands.json:/usr/share/nginx/html/commands.json:ro
    restart: unless-stopped
